/* Generated by cbindgen — do not edit.
 *
 * C header for raft-db FFI layer.
 * Link against libraftdb.a (static) or libraftdb.dylib/so (dynamic).
 */

#ifndef RAFT_DB_H
#define RAFT_DB_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
/* FFI feature is always active when this header is present. */
#define RAFT_DB_FFI


/**
 * Key length in bytes (AES-256).
 */
#define KEY_LEN 32

/**
 * Nonce length in bytes (GCM standard, 96 bits).
 */
#define NONCE_LEN 12

/**
 * Authentication tag length in bytes.
 */
#define TAG_LEN 16

/**
 * Bytes added to a plaintext by [`Cipher::seal`]: nonce prefix + GCM tag.
 */
#define SEAL_OVERHEAD (NONCE_LEN + TAG_LEN)

#if defined(RAFT_DB_FFI)
/**
 * Maximum accepted size, in bytes, of a document JSON envelope
 * (`rft_collection_put`, `rft_collection_put_auto`,
 * `rft_transaction_put`). Larger payloads are rejected with
 * [`RftError::PayloadTooLarge`].
 */
#define RFT_MAX_DOC_JSON_LEN ((16 * 1024) * 1024)
#endif

#if defined(RAFT_DB_FFI)
/**
 * Maximum accepted size, in bytes, of a query-spec JSON envelope
 * (`rft_query_execute`, `rft_observe_query`,
 * `rft_observe_query_dart_port`). Larger payloads are rejected with
 * [`RftError::PayloadTooLarge`].
 */
#define RFT_MAX_QUERY_JSON_LEN (64 * 1024)
#endif

/**
 * Maximum accepted record payload length when decoding (16 MiB).
 * Guards against corrupt/malicious length prefixes forcing huge allocations.
 */
#define MAX_RECORD_LEN ((16 * 1024) * 1024)

/**
 * Default maximum tolerated forward drift: 5 minutes.
 */
#define DEFAULT_MAX_DRIFT_MS ((5 * 60) * 1000)

/**
 * Maximum accepted payload length when decoding (16 MiB).
 *
 * A corrupt or malicious length prefix cannot force an arbitrarily large
 * allocation — anything above this bound is rejected as corruption.
 */
#define MAX_PAYLOAD_LEN ((16 * 1024) * 1024)

/**
 * Encoded size in bytes: 8 (physical) + 2 (logical).
 */
#define HlcTimestamp_ENCODED_SIZE (8 + 2)

#if defined(RAFT_DB_FFI)
/**
 * Error codes returned by all `rft_*` functions.
 *
 * Represented as a `#[repr(u32)]` enum for stable C ABI. Zero means
 * success; non-zero values indicate specific error conditions.
 */
enum RftError
#ifdef __cplusplus
  : uint32_t
#endif // __cplusplus
 {
#if defined(RAFT_DB_FFI)
    /**
     * Operation succeeded.
     */
    RFT_ERROR_OK = 0,
#endif
#if defined(RAFT_DB_FFI)
    /**
     * A required pointer argument was null.
     */
    RFT_ERROR_NULL_POINTER = 1,
#endif
#if defined(RAFT_DB_FFI)
    /**
     * A string argument was not valid UTF-8.
     */
    RFT_ERROR_INVALID_UTF8 = 2,
#endif
#if defined(RAFT_DB_FFI)
    /**
     * An I/O or storage engine error occurred.
     */
    RFT_ERROR_IO_ERROR = 3,
#endif
#if defined(RAFT_DB_FFI)
    /**
     * The requested key/document was not found.
     */
    RFT_ERROR_NOT_FOUND = 4,
#endif
#if defined(RAFT_DB_FFI)
    /**
     * The caller-provided buffer is too small. Check `out_len` for the
     * required size.
     */
    RFT_ERROR_BUFFER_TOO_SMALL = 5,
#endif
#if defined(RAFT_DB_FFI)
    /**
     * A document or filter passed via JSON failed to parse.
     */
    RFT_ERROR_INVALID_JSON = 6,
#endif
#if defined(RAFT_DB_FFI)
    /**
     * A transaction commit failed because a tracked document was modified
     * concurrently.
     */
    RFT_ERROR_TRANSACTION_CONFLICT = 7,
#endif
#if defined(RAFT_DB_FFI)
    /**
     * A handle (transaction, query result, subscription) is invalid —
     * already consumed, freed, or never created.
     */
    RFT_ERROR_INVALID_HANDLE = 8,
#endif
#if defined(RAFT_DB_FFI)
    /**
     * A subscription id passed to [`rft_unobserve`](super::rft_unobserve)
     * is not registered.
     */
    RFT_ERROR_UNKNOWN_SUBSCRIPTION = 9,
#endif
#if defined(RAFT_DB_FFI)
    /**
     * An internal panic was caught at the FFI boundary. The database
     * may be in an inconsistent in-memory state; the caller should
     * close and reopen the handle.
     */
    RFT_ERROR_INTERNAL_PANIC = 10,
#endif
#if defined(RAFT_DB_FFI)
    /**
     * A database path failed validation: empty, contains `..`
     * components, or escapes the confinement root passed to
     * [`rft_open_at`](super::rft_open_at) (including via symlinks).
     */
    RFT_ERROR_INVALID_PATH = 11,
#endif
#if defined(RAFT_DB_FFI)
    /**
     * A `rft_observe_*_dart_port` function was called before
     * [`rft_dart_init`](super::rft_dart_init) registered the Dart VM's
     * `Dart_PostCObject_DL` function.
     */
    RFT_ERROR_DART_API_NOT_INITIALIZED = 12,
#endif
#if defined(RAFT_DB_FFI)
    /**
     * A JSON envelope exceeds its size cap
     * ([`RFT_MAX_DOC_JSON_LEN`](super::RFT_MAX_DOC_JSON_LEN) for
     * documents, [`RFT_MAX_QUERY_JSON_LEN`](super::RFT_MAX_QUERY_JSON_LEN)
     * for query specs).
     */
    RFT_ERROR_PAYLOAD_TOO_LARGE = 13,
#endif
#if defined(RAFT_DB_FFI)
    /**
     * A JSON envelope declared a `"v"` schema version this build does
     * not support.
     */
    RFT_ERROR_UNSUPPORTED_VERSION = 14,
#endif
};
#ifndef __cplusplus
typedef uint32_t RftError;
#endif // __cplusplus
#endif

#if defined(RAFT_DB_FFI)
/**
 * Opaque handle wrapping a [`Database`] and its async runtime.
 *
 * Allocated on the heap by [`rft_open`](super::rft_open) and freed by
 * [`rft_close`](super::rft_close). C callers treat it as `*mut c_void`.
 */
typedef struct RaftDb RaftDb;
#endif

#if defined(RAFT_DB_FFI)
/**
 * Opaque query-result handle. Holds the snapshot of matching documents.
 */
typedef struct RaftQueryResult RaftQueryResult;
#endif

#if defined(RAFT_DB_FFI)
/**
 * Opaque transaction handle.
 */
typedef struct RaftTransaction RaftTransaction;
#endif

#if defined(RAFT_DB_FFI)
/**
 * Opaque engine-owned byte buffer. Returned by [`rft_collection_scan`];
 * read it via [`rft_buf_data`] / [`rft_buf_len`] and release it with
 * [`rft_buf_free`]. One scan = one engine pass = four FFI crossings
 * total, regardless of document count.
 */
typedef struct RftBuf RftBuf;
#endif

#if defined(RAFT_DB_FFI)
/**
 * C-compatible callback signature.
 *
 * `event_json` is a null-terminated UTF-8 string valid only for the
 * duration of the call. `user_data` is the opaque pointer passed to
 * [`rft_observe`].
 */
typedef void (*RftObserveCallback)(const char *event_json, void *user_data);
#endif

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

#if defined(RAFT_DB_FFI)
/**
 * Open or create a database at `path`.
 *
 * Returns a non-null handle on success, or null on failure (check
 * `out_err` for the error code).
 *
 * # Safety
 *
 * - `path` must be a valid null-terminated UTF-8 C string.
 * - `out_err` must be a valid pointer to an `RftError`.
 */
struct RaftDb *rft_open(const char *path, RftError *out_err);
#endif

#if defined(RAFT_DB_FFI)
/**
 * Open or create a database named `name` strictly inside the directory
 * `root` — the app-sandbox variant of [`rft_open`].
 *
 * Bindings should prefer this over `rft_open`, passing their platform's
 * app-private storage directory (`getFilesDir()` on Android,
 * Application Support on iOS/macOS) as `root`. `name` must be a
 * relative path; `..` components, absolute paths, and symlinks that
 * escape `root` are rejected with [`RftError::InvalidPath`].
 *
 * # Safety
 *
 * - `root` and `name` must be valid null-terminated UTF-8 C strings.
 * - `out_err` must be a valid pointer to an `RftError`, or null.
 */
struct RaftDb *rft_open_at(const char *root, const char *name, RftError *out_err);
#endif

#if defined(RAFT_DB_FFI)
/**
 * Close and free a database handle. Aborts any pending observer tasks,
 * then blocks until the observer runtime has fully shut down — after
 * this returns, no observer callback will ever fire again, so the
 * caller may safely free any `user_data` it passed to `rft_observe`.
 *
 * # Safety
 *
 * - `db` must be a handle returned by [`rft_open`], or null (no-op).
 *   Passing an already-closed or foreign pointer is a safe no-op.
 * - No other thread may be using `db` concurrently with this call.
 * - Must not be called from inside an observer callback (deadlock).
 * - After this call, `db` is dangling and must not be used.
 */
void rft_close(struct RaftDb *db);
#endif

#if defined(RAFT_DB_FFI)
/**
 * Insert or update a key-value pair on the raw engine.
 *
 * # Safety
 *
 * - `db` must be a valid, non-null handle from [`rft_open`].
 * - `key` must point to at least `key_len` readable bytes.
 * - `value` must point to at least `value_len` readable bytes.
 */
RftError rft_put(struct RaftDb *db,
                 const uint8_t *key,
                 uintptr_t key_len,
                 const uint8_t *value,
                 uintptr_t value_len);
#endif

#if defined(RAFT_DB_FFI)
/**
 * Look up a key on the raw engine.
 *
 * On success, writes the value into the caller-provided buffer at
 * `out_value` and sets `*out_len` to the number of bytes written.
 *
 * If the buffer is too small, returns [`RftError::BufferTooSmall`] and
 * sets `*out_len` to the required size (no bytes are written).
 *
 * If the key is not found, returns [`RftError::NotFound`].
 *
 * # Safety
 *
 * - `db` must be a valid, non-null handle from [`rft_open`].
 * - `key` must point to at least `key_len` readable bytes.
 * - `out_value` must point to a buffer of at least `*out_len` writable
 *   bytes, or be null if only querying the required size.
 * - `out_len` must be a valid, non-null pointer to a `usize`.
 */
RftError rft_get(struct RaftDb *db,
                 const uint8_t *key,
                 uintptr_t key_len,
                 uint8_t *out_value,
                 uintptr_t *out_len);
#endif

#if defined(RAFT_DB_FFI)
/**
 * Delete a key on the raw engine.
 *
 * Returns [`RftError::Ok`] on success. Deleting a non-existent key is
 * not an error (it writes a tombstone).
 *
 * # Safety
 *
 * - `db` must be a valid, non-null handle from [`rft_open`].
 * - `key` must point to at least `key_len` readable bytes.
 */
RftError rft_delete(struct RaftDb *db, const uint8_t *key, uintptr_t key_len);
#endif

#if defined(RAFT_DB_FFI)
/**
 * Pointer to the buffer's bytes. Valid until [`rft_buf_free`].
 *
 * # Safety
 *
 * `buf` must be a live handle from [`rft_collection_scan`] (or null,
 * which yields null).
 */
const uint8_t *rft_buf_data(const struct RftBuf *buf);
#endif

#if defined(RAFT_DB_FFI)
/**
 * Length in bytes of the buffer. Null yields 0.
 *
 * # Safety
 *
 * `buf` must be a live handle from [`rft_collection_scan`] or null.
 */
uintptr_t rft_buf_len(const struct RftBuf *buf);
#endif

#if defined(RAFT_DB_FFI)
/**
 * Free a buffer handle. Null is a no-op. After this call the handle and
 * any pointer previously returned by [`rft_buf_data`] are dangling.
 *
 * # Safety
 *
 * `buf` must be a handle from [`rft_collection_scan`] not yet freed, or
 * null.
 */
void rft_buf_free(struct RftBuf *buf);
#endif

#if defined(RAFT_DB_FFI)
/**
 * Insert or update every document in `batch` (binary batch encoding)
 * atomically: one transaction, one WAL write, one fsync. Document ids
 * are honoured; repeated ids within the batch apply in order (last one
 * wins).
 *
 * The whole batch is validated before anything is written — a malformed
 * document rejects the entire call with no partial effects.
 *
 * # Safety
 *
 * - `db` must be a valid handle from [`rft_open`](super::rft_open).
 * - `collection` must be a valid null-terminated UTF-8 C string.
 * - `batch` must point to `batch_len` readable bytes (null only if
 *   `batch_len == 0`).
 */
RftError rft_collection_put_many(struct RaftDb *db,
                                 const char *collection,
                                 const uint8_t *batch,
                                 uintptr_t batch_len);
#endif

#if defined(RAFT_DB_FFI)
/**
 * Delete every id in `ids` atomically: one transaction, one WAL write,
 * one fsync. Missing ids are not an error (tombstones are written).
 *
 * # Safety
 *
 * - `db` must be a valid handle; `collection` a valid null-terminated
 *   UTF-8 C string.
 * - `ids` must point to `count` readable `u64`s (null only if
 *   `count == 0`).
 */
RftError rft_collection_delete_many(struct RaftDb *db,
                                    const char *collection,
                                    const uint64_t *ids,
                                    uintptr_t count);
#endif

#if defined(RAFT_DB_FFI)
/**
 * Read every document in `collection` in one call. On success writes a
 * new buffer handle (binary batch encoding, ids ascending) to
 * `*out_buf`; the caller owns it and must release it with
 * [`rft_buf_free`].
 *
 * # Safety
 *
 * - `db` must be a valid handle; `collection` a valid null-terminated
 *   UTF-8 C string; `out_buf` a writable `*mut *mut RftBuf`.
 */
RftError rft_collection_scan(struct RaftDb *db, const char *collection, struct RftBuf **out_buf);
#endif

#if defined(RAFT_DB_FFI)
/**
 * Fetch one document by id as binary codec bytes — the single-lookup
 * replacement for the two-phase JSON `rft_collection_get`. `*out_len`
 * carries the buffer capacity in and the written (or required) size
 * out; on `BufferTooSmall` nothing is copied and the caller retries
 * with a larger buffer (rare when reusing a sensibly-sized one).
 *
 * # Safety
 *
 * - `db` must be a valid handle; `collection` a valid null-terminated
 *   UTF-8 C string.
 * - `out_len` must be a valid `*mut usize`; `out_buf` must point to
 *   `*out_len` writable bytes (or be null to only query the size).
 */
RftError rft_collection_get_buf(struct RaftDb *db,
                                const char *collection,
                                uint64_t doc_id,
                                uint8_t *out_buf,
                                uintptr_t *out_len);
#endif

#if defined(RAFT_DB_FFI)
/**
 * Insert or update a document in `collection`. The document's `id` field
 * is honoured. The same id always maps to the same slot — repeated puts
 * overwrite (and bump the internal version).
 *
 * # Safety
 *
 * - `db` must be a valid handle returned by [`rft_open`](super::rft_open).
 * - `collection` must be a valid null-terminated UTF-8 C string.
 * - `doc_json` must be a valid UTF-8 buffer of `doc_json_len` bytes.
 */
RftError rft_collection_put(struct RaftDb *db,
                            const char *collection,
                            const uint8_t *doc_json,
                            uintptr_t doc_json_len);
#endif

#if defined(RAFT_DB_FFI)
/**
 * Insert a document, letting the database assign a fresh id. Writes the
 * assigned id to `*out_doc_id` on success.
 *
 * # Safety
 *
 * - All non-null pointers must point to valid memory of the appropriate
 *   size; `out_doc_id` must be a writable `*mut u64`.
 */
RftError rft_collection_put_auto(struct RaftDb *db,
                                 const char *collection,
                                 const uint8_t *doc_json,
                                 uintptr_t doc_json_len,
                                 uint64_t *out_doc_id);
#endif

#if defined(RAFT_DB_FFI)
/**
 * Fetch a document by id, writing its JSON encoding to `out_buf`. On
 * `BufferTooSmall` the required size is written to `*out_len` and no
 * bytes are copied.
 *
 * # Safety
 *
 * - `db` must be a valid handle.
 * - `collection` must be a valid null-terminated UTF-8 C string.
 * - `out_buf` must be writable for `*out_len` bytes, or null to query
 *   the required size.
 * - `out_len` must be a valid `*mut usize`.
 */
RftError rft_collection_get(struct RaftDb *db,
                            const char *collection,
                            uint64_t doc_id,
                            uint8_t *out_buf,
                            uintptr_t *out_len);
#endif

#if defined(RAFT_DB_FFI)
/**
 * Delete a document. Returns [`RftError::Ok`] whether the document
 * existed or not.
 *
 * # Safety
 *
 * - `db` must be a valid handle.
 * - `collection` must be a valid null-terminated UTF-8 C string.
 */
RftError rft_collection_delete(struct RaftDb *db, const char *collection, uint64_t doc_id);
#endif

#if defined(RAFT_DB_FFI)
/**
 * Number of documents in `collection`. Writes the count to `*out_count`.
 *
 * # Safety
 *
 * - `db` must be a valid handle.
 * - `collection` must be a valid null-terminated UTF-8 C string.
 * - `out_count` must be a valid `*mut usize`.
 */
RftError rft_collection_count(struct RaftDb *db, const char *collection, uintptr_t *out_count);
#endif

#if defined(RAFT_DB_FFI)
/**
 * List all document ids in `collection`, sorted ascending.
 *
 * Writes up to `*out_len` ids into `out_ids` and sets `*out_len` to
 * the number written. If `out_ids` is null or `*out_len` is smaller
 * than the total count, returns [`RftError::BufferTooSmall`] and
 * `*out_len` holds the required size.
 *
 * # Safety
 *
 * - `db` must be a valid handle.
 * - `collection` must be a valid null-terminated UTF-8 C string.
 * - `out_ids` must be writable for `*out_len * 8` bytes, or null.
 * - `out_len` must be a valid `*mut usize`.
 */
RftError rft_collection_list_ids(struct RaftDb *db,
                                 const char *collection,
                                 uint64_t *out_ids,
                                 uintptr_t *out_len);
#endif

#if defined(RAFT_DB_FFI)
/**
 * Register the Dart VM's `Dart_PostCObject_DL` function so observers
 * can deliver events to Dart `SendPort`s.
 *
 * Dart callers pass `NativeApi.postCObject.address` (from `dart:ffi`).
 * Must be called once per process before any `rft_observe_*_dart_port`
 * call; calling it again is harmless.
 *
 * # Safety
 *
 * - `post_cobject_fn` must be the address of the Dart VM's
 *   `Dart_PostCObject_DL` function (or a function with an identical
 *   ABI), and must remain valid for the lifetime of the process.
 */
RftError rft_dart_init(void *post_cobject_fn);
#endif

#if defined(RAFT_DB_FFI)
/**
 * Register a collection observer that delivers each mutation event to
 * the Dart `SendPort` `port` as a JSON string (same payload as
 * [`rft_observe`](super::rft_observe)).
 *
 * Requires a prior successful [`rft_dart_init`]; otherwise returns
 * [`RftError::DartApiNotInitialized`]. Cancel with
 * [`rft_unobserve`](super::rft_unobserve); closing the Dart
 * `ReceivePort` alone stops delivery but leaks the background task
 * until `rft_unobserve` or `rft_close`.
 *
 * # Safety
 *
 * - `db` must be a valid handle.
 * - `collection` must be a valid null-terminated UTF-8 C string.
 * - `port` must be a native port id obtained from a Dart `ReceivePort`.
 * - `out_sub_id` must be a valid `*mut u64`.
 */
RftError rft_observe_dart_port(struct RaftDb *db,
                               const char *collection,
                               int64_t port,
                               uint64_t *out_sub_id);
#endif

#if defined(RAFT_DB_FFI)
/**
 * Register a live-query observer that delivers each
 * [`QueryDiff`](crate::reactive::QueryDiff) to the Dart `SendPort`
 * `port` as a JSON string (same payload and initial-snapshot semantics
 * as [`rft_observe_query`](super::rft_observe_query)).
 *
 * Requires a prior successful [`rft_dart_init`]; otherwise returns
 * [`RftError::DartApiNotInitialized`].
 *
 * # Safety
 *
 * - `db` must be a valid handle.
 * - `query_json` must be a valid UTF-8 buffer of `query_json_len` bytes.
 * - `port` must be a native port id obtained from a Dart `ReceivePort`.
 * - `out_sub_id` must be a valid `*mut u64`.
 */
RftError rft_observe_query_dart_port(struct RaftDb *db,
                                     const uint8_t *query_json,
                                     uintptr_t query_json_len,
                                     int64_t port,
                                     uint64_t *out_sub_id);
#endif

#if defined(RAFT_DB_FFI)
/**
 * Register an observer callback for `collection`. The callback fires
 * whenever a document in that collection is inserted, updated, or
 * deleted.
 *
 * Returns a non-zero subscription id via `out_sub_id` on success. Pass
 * it to [`rft_unobserve`] to cancel the subscription.
 *
 * # Safety
 *
 * - `db` must be a valid handle.
 * - `collection` must be a valid null-terminated UTF-8 C string.
 * - `callback` must be a valid C function pointer that remains valid
 *   until [`rft_unobserve`] returns.
 * - `user_data` is opaque to Rust; the platform binding is responsible
 *   for managing its lifetime so it remains valid for the subscription.
 * - `out_sub_id` must be a valid `*mut u64`.
 */
RftError rft_observe(struct RaftDb *db,
                     const char *collection,
                     RftObserveCallback callback,
                     void *user_data,
                     uint64_t *out_sub_id);
#endif

#if defined(RAFT_DB_FFI)
/**
 * Register a *live query* subscription for `query_json`. The callback
 * fires immediately with an initial-snapshot diff (every matching
 * document in `added`, others empty) and then again every time a
 * mutation in the queried collection causes the result set to change.
 *
 * Each diff is delivered as JSON:
 *
 * ```json
 * {
 *   "added":   [<Document>, ...],
 *   "removed": [<Document>, ...],
 *   "updated": [<Document>, ...]
 * }
 * ```
 *
 * # Safety
 *
 * - `db` must be a valid handle.
 * - `query_json` must be a valid UTF-8 buffer of `query_json_len` bytes.
 * - `callback` must be a valid C function pointer that remains valid
 *   until [`rft_unobserve`] returns.
 * - `user_data` is opaque to Rust; the platform binding owns its
 *   lifetime and must keep it valid for the subscription.
 * - `out_sub_id` must be a valid `*mut u64`.
 */
RftError rft_observe_query(struct RaftDb *db,
                           const uint8_t *query_json,
                           uintptr_t query_json_len,
                           RftObserveCallback callback,
                           void *user_data,
                           uint64_t *out_sub_id);
#endif

#if defined(RAFT_DB_FFI)
/**
 * Cancel a subscription previously created by [`rft_observe`] or
 * [`rft_observe_query`]. Aborts the background task and removes it
 * from the registry. Calling this with an unknown id returns
 * [`RftError::UnknownSubscription`].
 *
 * # Safety
 *
 * - `db` must be a valid handle.
 */
RftError rft_unobserve(struct RaftDb *db, uint64_t sub_id);
#endif

#if defined(RAFT_DB_FFI)
/**
 * Execute a query and return an opaque result handle. Caller must free
 * it with [`rft_query_result_free`].
 *
 * # Safety
 *
 * - `db` must be a valid handle.
 * - `query_json` must be a valid UTF-8 buffer of `query_json_len` bytes.
 * - `out_result` must be a valid `*mut *mut RaftQueryResult`.
 */
RftError rft_query_execute(struct RaftDb *db,
                           const uint8_t *query_json,
                           uintptr_t query_json_len,
                           struct RaftQueryResult **out_result);
#endif

#if defined(RAFT_DB_FFI)
/**
 * Number of documents in a query result. Returns 0 for null, freed, or
 * otherwise invalid handles.
 *
 * # Safety
 *
 * - `result` must be a handle returned by [`rft_query_execute`], or null.
 */
uintptr_t rft_query_result_count(const struct RaftQueryResult *result);
#endif

#if defined(RAFT_DB_FFI)
/**
 * Fetch the JSON encoding of the document at `index` in the result set.
 * On `BufferTooSmall` the required size is written to `*out_len`.
 *
 * # Safety
 *
 * - `result` must be a handle returned by [`rft_query_execute`].
 * - `out_buf` must be writable for `*out_len` bytes, or null to query
 *   the required size.
 * - `out_len` must be a valid `*mut usize`.
 */
RftError rft_query_result_get(const struct RaftQueryResult *result,
                              uintptr_t index,
                              uint8_t *out_buf,
                              uintptr_t *out_len);
#endif

#if defined(RAFT_DB_FFI)
/**
 * Free a query result handle. Safe to call with null (no-op). Freeing
 * an already-freed or foreign pointer is also a safe no-op.
 *
 * # Safety
 *
 * - `result` must be a handle returned by [`rft_query_execute`], or null.
 * - After this call, `result` is dangling and must not be reused.
 */
void rft_query_result_free(struct RaftQueryResult *result);
#endif

#if defined(RAFT_DB_FFI)
/**
 * Begin a new transaction. The caller takes ownership of the returned
 * handle and must end it with `commit` or `rollback`.
 *
 * # Safety
 *
 * - `db` must be a valid handle.
 * - `out_txn` must be a valid `*mut *mut RaftTransaction`.
 */
RftError rft_transaction_begin(struct RaftDb *db, struct RaftTransaction **out_txn);
#endif

#if defined(RAFT_DB_FFI)
/**
 * Read a document inside the transaction. The version is recorded for
 * conflict detection at commit time. JSON encoding is written to
 * `out_buf` using the same buffer-too-small protocol as
 * `rft_collection_get`.
 *
 * Returns [`RftError::NotFound`] when the doc does not exist (the read
 * is still tracked, so insertion of the doc by another writer before
 * commit will be detected as a conflict).
 *
 * # Safety
 *
 * - `txn` must be a valid handle returned by
 *   [`rft_transaction_begin`] and not yet committed/rolled back.
 * - Other arguments follow the standard FFI contract.
 */
RftError rft_transaction_get(struct RaftTransaction *txn,
                             const char *collection,
                             uint64_t doc_id,
                             uint8_t *out_buf,
                             uintptr_t *out_len);
#endif

#if defined(RAFT_DB_FFI)
/**
 * Buffer a write inside the transaction. Applied atomically on commit.
 *
 * # Safety
 *
 * - `txn` must be a valid handle returned by
 *   [`rft_transaction_begin`] and not yet finalised.
 * - `doc_json` must be a valid UTF-8 buffer of `doc_json_len` bytes.
 */
RftError rft_transaction_put(struct RaftTransaction *txn,
                             const char *collection,
                             const uint8_t *doc_json,
                             uintptr_t doc_json_len);
#endif

#if defined(RAFT_DB_FFI)
/**
 * Buffer a delete inside the transaction.
 *
 * # Safety
 *
 * - `txn` must be a valid, active handle.
 * - `collection` must be a valid null-terminated UTF-8 C string.
 */
RftError rft_transaction_delete(struct RaftTransaction *txn,
                                const char *collection,
                                uint64_t doc_id);
#endif

#if defined(RAFT_DB_FFI)
/**
 * Validate the read set and atomically apply all buffered changes.
 * Consumes the handle — it is freed regardless of outcome and must not
 * be used again.
 *
 * Returns:
 * - [`RftError::Ok`] on success.
 * - [`RftError::TransactionConflict`] if a tracked doc was modified
 *   concurrently. No writes are applied.
 *
 * # Safety
 *
 * - `txn` must be a valid, active handle. After this call, `txn` is
 *   freed and dangling.
 */
RftError rft_transaction_commit(struct RaftTransaction *txn);
#endif

#if defined(RAFT_DB_FFI)
/**
 * Discard the transaction without applying any buffered changes.
 * Consumes the handle.
 *
 * # Safety
 *
 * - `txn` must be a valid handle returned by
 *   [`rft_transaction_begin`], or null (no-op).
 * - After this call, `txn` is freed and dangling.
 */
void rft_transaction_rollback(struct RaftTransaction *txn);
#endif

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* RAFT_DB_H */
