/* Generated by cbindgen — do not edit.
 *
 * C header for raft-db FFI layer.
 * Link against libraftdb.a (static) or libraftdb.dylib/so (dynamic).
 */

#ifndef RAFT_DB_H
#define RAFT_DB_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
/* FFI feature is always active when this header is present. */
#define RAFT_DB_FFI


/**
 * Encoded size in bytes: 8 (physical) + 2 (logical).
 */
#define HlcTimestamp_ENCODED_SIZE (8 + 2)

#if defined(RAFT_DB_FFI)
/**
 * Error codes returned by all `rft_*` functions.
 *
 * Represented as a `#[repr(u32)]` enum for stable C ABI. Zero means
 * success; non-zero values indicate specific error conditions.
 */
enum RftError
#ifdef __cplusplus
  : uint32_t
#endif // __cplusplus
 {
#if defined(RAFT_DB_FFI)
    /**
     * Operation succeeded.
     */
    RFT_ERROR_OK = 0,
#endif
#if defined(RAFT_DB_FFI)
    /**
     * A required pointer argument was null.
     */
    RFT_ERROR_NULL_POINTER = 1,
#endif
#if defined(RAFT_DB_FFI)
    /**
     * A string argument was not valid UTF-8.
     */
    RFT_ERROR_INVALID_UTF8 = 2,
#endif
#if defined(RAFT_DB_FFI)
    /**
     * An I/O or storage engine error occurred.
     */
    RFT_ERROR_IO_ERROR = 3,
#endif
#if defined(RAFT_DB_FFI)
    /**
     * The requested key was not found.
     */
    RFT_ERROR_NOT_FOUND = 4,
#endif
#if defined(RAFT_DB_FFI)
    /**
     * The caller-provided buffer is too small. Check `out_len` for the
     * required size.
     */
    RFT_ERROR_BUFFER_TOO_SMALL = 5,
#endif
};
#ifndef __cplusplus
typedef uint32_t RftError;
#endif // __cplusplus
#endif

#if defined(RAFT_DB_FFI)
/**
 * Opaque handle wrapping a [`StorageEngine`].
 *
 * Allocated on the heap by [`rft_open`](super::rft_open) and freed by
 * [`rft_close`](super::rft_close). C callers treat it as `*mut c_void`.
 */
typedef struct RaftDb RaftDb;
#endif

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

#if defined(RAFT_DB_FFI)
/**
 * Open or create a database at `path`.
 *
 * Returns a non-null handle on success, or null on failure (check
 * `out_err` for the error code).
 *
 * # Safety
 *
 * - `path` must be a valid null-terminated UTF-8 C string.
 * - `out_err` must be a valid pointer to an `RftError`.
 */
rft_ struct RaftDb *rft_open(const char *path, RftError *out_err);
#endif

#if defined(RAFT_DB_FFI)
/**
 * Close and free a database handle.
 *
 * # Safety
 *
 * - `db` must be a handle returned by [`rft_open`], or null (no-op).
 * - After this call, `db` is dangling and must not be used.
 */
rft_ void rft_close(struct RaftDb *db);
#endif

#if defined(RAFT_DB_FFI)
/**
 * Insert or update a key-value pair.
 *
 * # Safety
 *
 * - `db` must be a valid, non-null handle from [`rft_open`].
 * - `key` must point to at least `key_len` readable bytes.
 * - `value` must point to at least `value_len` readable bytes.
 */
rft_
RftError rft_put(struct RaftDb *db,
                 const uint8_t *key,
                 uintptr_t key_len,
                 const uint8_t *value,
                 uintptr_t value_len);
#endif

#if defined(RAFT_DB_FFI)
/**
 * Look up a key.
 *
 * On success, writes the value into the caller-provided buffer at
 * `out_value` and sets `*out_len` to the number of bytes written.
 *
 * If the buffer is too small, returns [`RftError::BufferTooSmall`] and
 * sets `*out_len` to the required size (no bytes are written).
 *
 * If the key is not found, returns [`RftError::NotFound`].
 *
 * # Safety
 *
 * - `db` must be a valid, non-null handle from [`rft_open`].
 * - `key` must point to at least `key_len` readable bytes.
 * - `out_value` must point to a buffer of at least `*out_len` writable
 *   bytes, or be null if only querying the required size.
 * - `out_len` must be a valid, non-null pointer to a `usize`.
 */
rft_
RftError rft_get(struct RaftDb *db,
                 const uint8_t *key,
                 uintptr_t key_len,
                 uint8_t *out_value,
                 uintptr_t *out_len);
#endif

#if defined(RAFT_DB_FFI)
/**
 * Delete a key.
 *
 * Returns [`RftError::Ok`] on success. Deleting a non-existent key is
 * not an error (it writes a tombstone).
 *
 * # Safety
 *
 * - `db` must be a valid, non-null handle from [`rft_open`].
 * - `key` must point to at least `key_len` readable bytes.
 */
rft_ RftError rft_delete(struct RaftDb *db, const uint8_t *key, uintptr_t key_len);
#endif

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* RAFT_DB_H */
