//! Property-based convergence suites for the CRDT primitives (X3).
//!
//! Every `Merge` implementation must be a join on the state lattice:
//! commutative, associative, and idempotent. Replicas are generated by
//! replaying arbitrary operation sequences, so the properties are checked
//! over realistic reachable states rather than hand-picked examples.

use proptest::prelude::*;

use raftdb::crdt::{Counter, LwwRegister, Merge, OrSet};
use raftdb::wal::HlcTimestamp;

fn ts(physical: u64, logical: u16) -> HlcTimestamp {
    HlcTimestamp::new(physical, logical)
}

/// Merge in a fresh copy so the original stays untouched.
fn merged<T: Merge + Clone>(a: &T, b: &T) -> T {
    let mut out = a.clone();
    out.merge(b);
    out
}

// ── LWW register ───────────────────────────────────────────────────────

/// An arbitrary register write: value + HLC + device.
fn lww_strategy() -> impl Strategy<Value = LwwRegister<u32>> {
    (any::<u32>(), 0..1_000u64, 0..8u16, 1..5u128).prop_map(|(v, physical, logical, device)| {
        LwwRegister::new(v, ts(physical, logical), device)
    })
}

// ── OR-Set built from an operation log ─────────────────────────────────

#[derive(Debug, Clone)]
enum SetOp {
    Add {
        element: u8,
        device: u128,
        at: HlcTimestamp,
    },
    Remove {
        element: u8,
    },
}

fn set_op_strategy() -> impl Strategy<Value = SetOp> {
    prop_oneof![
        (0..16u8, 1..4u128, 0..100u64, 0..4u16).prop_map(|(element, device, p, l)| SetOp::Add {
            element,
            device,
            at: ts(p, l),
        }),
        (0..16u8).prop_map(|element| SetOp::Remove { element }),
    ]
}

fn orset_from_ops(ops: &[SetOp]) -> OrSet<u8> {
    // HLC guarantees every add gets a globally unique (device, timestamp)
    // tag; the generator's small ranges collide, so skip duplicate tags to
    // keep replay within the states reachable under that invariant.
    let mut used_tags = std::collections::HashSet::new();
    let mut set = OrSet::new();
    for op in ops {
        match op {
            SetOp::Add {
                element,
                device,
                at,
            } => {
                if used_tags.insert((*device, *at)) {
                    set.add(*element, *device, *at);
                }
            }
            SetOp::Remove { element } => {
                set.remove(element);
            }
        }
    }
    set
}

fn orset_strategy() -> impl Strategy<Value = OrSet<u8>> {
    prop::collection::vec(set_op_strategy(), 0..24).prop_map(|ops| orset_from_ops(&ops))
}

// ── PN-Counter built from an operation log ─────────────────────────────

fn counter_from_ops(ops: &[(u128, i64)]) -> Counter {
    let mut c = Counter::new();
    for (device, amount) in ops {
        c.increment(*device, *amount);
    }
    c
}

fn counter_strategy() -> impl Strategy<Value = Counter> {
    prop::collection::vec((1..4u128, -100..100i64), 0..24).prop_map(|ops| counter_from_ops(&ops))
}

// ── Lattice laws, per type ─────────────────────────────────────────────

macro_rules! lattice_laws {
    ($mod_name:ident, $strategy:expr) => {
        mod $mod_name {
            use super::*;

            proptest! {
                #[test]
                fn merge_is_commutative(a in $strategy, b in $strategy) {
                    prop_assert_eq!(merged(&a, &b), merged(&b, &a));
                }

                #[test]
                fn merge_is_associative(a in $strategy, b in $strategy, c in $strategy) {
                    let left = merged(&merged(&a, &b), &c);
                    let right = merged(&a, &merged(&b, &c));
                    prop_assert_eq!(left, right);
                }

                #[test]
                fn merge_is_idempotent(a in $strategy, b in $strategy) {
                    let once = merged(&a, &b);
                    let twice = merged(&once, &b);
                    prop_assert_eq!(once, twice);
                    // Self-merge is also a no-op.
                    prop_assert_eq!(merged(&a, &a), a);
                }
            }
        }
    };
}

lattice_laws!(lww_laws, lww_strategy());
lattice_laws!(orset_laws, orset_strategy());
lattice_laws!(counter_laws, counter_strategy());

// ── Type-specific convergence semantics ────────────────────────────────

proptest! {
    /// Two replicas that each saw a disjoint half of the operations
    /// converge to the same state regardless of merge direction, and the
    /// counter value is the sum of every operation's saturated effect.
    #[test]
    fn counter_disjoint_devices_sum(
        ops_a in prop::collection::vec((1..3u128, -50..50i64), 0..16),
        ops_b in prop::collection::vec((3..5u128, -50..50i64), 0..16),
    ) {
        let a = counter_from_ops(&ops_a);
        let b = counter_from_ops(&ops_b);
        let ab = merged(&a, &b);
        prop_assert_eq!(ab.clone(), merged(&b, &a));
        prop_assert_eq!(ab.value(), a.value() + b.value());
    }

    /// Add-wins: an add concurrent with a remove (the remove never
    /// observed the add's tag) survives the merge on both replicas.
    #[test]
    fn orset_concurrent_add_wins(
        element in 0..16u8,
        p in 0..100u64,
        device_a in 1..3u128,
        device_b in 3..5u128,
    ) {
        let mut shared = OrSet::new();
        shared.add(element, device_a, ts(p, 0));

        // Replica A removes; replica B concurrently re-adds with a fresh tag.
        let mut a = shared.clone();
        a.remove(&element);
        let mut b = shared;
        b.add(element, device_b, ts(p + 1, 0));

        prop_assert!(merged(&a, &b).contains(&element));
        prop_assert!(merged(&b, &a).contains(&element));
    }

    /// A stale replica still carrying a tombstoned tag cannot resurrect
    /// a removed element.
    #[test]
    fn orset_no_resurrection_from_stale_replica(
        element in 0..16u8,
        p in 0..100u64,
        device in 1..4u128,
    ) {
        let mut stale = OrSet::new();
        stale.add(element, device, ts(p, 0));

        let mut current = stale.clone();
        current.remove(&element);

        prop_assert!(!merged(&current, &stale).contains(&element));
        prop_assert!(!merged(&stale, &current).contains(&element));
    }

    /// LWW registers on two replicas converge to the same winner in
    /// either merge order.
    #[test]
    fn lww_replicas_converge(a in lww_strategy(), b in lww_strategy()) {
        let ab = merged(&a, &b);
        let ba = merged(&b, &a);
        prop_assert_eq!(ab.value(), ba.value());
        prop_assert_eq!(ab.timestamp(), ba.timestamp());
        prop_assert_eq!(ab.device_id(), ba.device_id());
    }
}
